# Generated by Django 6.0.6 on 2026-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_precio_distribuidor_producto_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
