# Generated by Django 6.0.6 on 2026-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
