# Generated by Django 6.0.6 on 2026-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('pagado', 'Pagado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
