# Generated by Django 6.0.6 on 2026-06-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('propietario', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
