# Generated by Django 6.0.6 on 2026-06-30 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        ('pedidos', '0002_detallepedido_devuelto_pedido_facturado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('total', 'Devolucion Total'), ('parcial', 'Devolucion Parcial'), ('cambio_talla', 'Cambio por Talla'), ('cambio_producto', 'Cambio por Producto'), ('defectuoso', 'Producto Defectuoso'), ('garantia', 'Garantia')], max_length=20)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('28', '28'), ('30', '30'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=5)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado_producto', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('defectuoso', 'Defectuoso'), ('danado', 'Danado')], default='nuevo', max_length=12)),
                ('vuelve_a_inventario', models.BooleanField(default=True)),
                ('talla_nueva', models.CharField(blank=True, choices=[('28', '28'), ('30', '30'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=5, null=True)),
                ('procesado', models.BooleanField(default=False, help_text='Indica si ya se aplicaron los efectos sobre inventario.')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='pedidos.detallepedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_detalle', to='catalogo.producto')),
                ('producto_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_recibidos', to='catalogo.producto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='devoluciones.devolucion')),
            ],
            options={
                'verbose_name': 'Detalle de Devolucion',
                'verbose_name_plural': 'Detalles de Devolucion',
            },
        ),
        migrations.CreateModel(
            name='MovimientoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='devoluciones.detalledevolucion')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='devoluciones.devolucion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_devolucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Devolucion',
                'verbose_name_plural': 'Movimientos de Devolucion',
                'ordering': ['-fecha'],
            },
        ),
    ]
